# Generated by Django 4.2.7 on 2024-02-03 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_product_category_product_product_images_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('contact_first_name', models.CharField(max_length=25)),
                ('contact_last_name', models.CharField(max_length=25)),
                ('contact_email', models.CharField(max_length=60)),
                ('contact_phone', models.IntegerField(default=0, max_length=25)),
                ('contact_desc', models.CharField(max_length=500)),
            ],
        ),
    ]
