# Generated by Django 4.2.7 on 2024-02-12 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0007_billingquantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingquantity',
            name='name',
        ),
        migrations.RemoveField(
            model_name='billingquantity',
            name='price',
        ),
        migrations.AddField(
            model_name='billingquantity',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='shop.product'),
        ),
        migrations.AddField(
            model_name='billingquantity',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='billingquantity',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
